### ISSUE TITLE
tinytex/

### ISSUE THREAD

**Issue by yihui** [yihui/yihui.org#104]
Manually creating this issue for Utterances comments at https://yihui.org/tinytex/

**Comment by shrektan** [comment]
公司服务器没有互联网链接，最近两天鼓捣了会TexLive，想看看怎么才能弄一个离线的Repo。然后，我发现真是太乱了…真看不懂…

**Comment by yihui** [comment]
这个你可以早一点问我，就不必浪费这个时间了。其实我已经把 TeX Live 全集都打包好了，只不过我还没昭告天下而已（因为我还没确定最终把这些超级大包存在哪里，是放我个人 Github 账号里还是转移到公司账号下）。全集是 TinyTeX-2：https://github.com/yihui/tinytex-releases/releases/tag/daily

通过 R 安装：

```r
tinytex:::install_prebuilt('TinyTeX-2')
```

或者通过脚本安装皆可：https://yihui.org/tinytex/#installation 设置环境变量 `TINYTEX_INSTALLER=TinyTeX-2`。

当然，你也可以直接下载文件，解压缩到合适的位置。

这个精简版的全集体积比官方应该是能小一半的。装它之后就不必再担心缺包了。

**Comment by shrektan** [comment]
本以为这个需求能很快找到答案，我还是低估了LaTeX的复杂程度！太赞了，我马上试试，谢谢！

**Comment by yihui** [comment]
嗯，架设一个可以离线使用的仓库估计是会有点复杂，但打包所有的 LaTeX 包就简单多了。既然架设库的主要目的是为了装缺失的包，那还不如就整锅端下来后一劳永逸了。

**Comment by shrektan** [comment]
是的。其实我本来就是想全装，但tlmgr install scheme-full 在最后一步老是报错，原因不详，已放弃。现在直接一步到位，非常开心，正合我意。

**Comment by yihui** [comment]
嗯，是的，这个命令确实是有出错的可能，我也一样读不懂错误消息、不明白原因。比如在 AppVeyor 平台上的 macOS 系统就会出错，我直接加个 `|| true` 给暴力忽略了错误：https://github.com/yihui/tinytex-releases/blob/4149573c79eae0d0d722218e0420d799f2c76cc1/appveyor.yml#L96 我试过在 Github Actions 的三大操作系统上运行也会出错，同样原因不详，所以现在我依然在用 AppVeyor 打包。

**Comment by Teddy-van-Jerry** [comment]
您好，我现在正在做一个仿真软件（[mmCEsim](https://github.com/mmcesim)）可以自动导出并编译 LaTeX 报告，仅在软件安装包里给用户提供 minimal 的 packages。我想是不是可以直接利用您在 `tools` 里的代码配合上 GitHub Actions 直接进行 build 呢？不确定是不是修改 `tools/pkgs-custom.txt` 还是 `tools/pkgs-yihui.txt`，再调整对应的 `build.yml` 内容即可实现 :-)

**Comment by yihui** [comment]
@Teddy-van-Jerry 是的，不过更简单的办法是你先安装 [`TinyTeX-0`](https://github.com/rstudio/tinytex-releases#releases)，在此基础上再用 `tlmgr install` 添加你需要的其它包，最后将 TinyTeX 文件夹打包发行。当然，用你说的办法从头编译也是可以的，只是稍微啰嗦一点。

**Comment by Teddy-van-Jerry** [comment]
哦哦明白啦，非常感谢！
