### ISSUE TITLE
Change of comment engines?

### ISSUE THREAD

**Issue by liutiming** [yihui/yihui.org#120]
Hi Yihui, I noticed that there is now utterance on yihui.org. Just wondering if you plan to switch to that or if you are just providing more options? 

I wonder if I should set that up too but there is a slight concern of fragmenting discussions and losing the economies of scale? (of course there is no scale on my website now, anyways).

---edit
I realise I opened the issue because I have been thinking about the philosophy of splitting for a while, haha. It is similar to programming in a way: when is it best to have two modules so they are specialised and cater to specific needs, and when is it best to have a combined module because it is more maintainable. [The philosophy of softare design](https://amzn.to/2PbdlIY) had some discussion on this.

**Comment by yihui** [comment]
I added Utterances for two reasons: 1. I don't like the way that Disqus tracks users. 2. Disqus is blocked in a certain country. Unfortunately I've used Disqus for too many years and can't easily get rid of it.
