### ISSUE TITLE
网站文章分类

### ISSUE THREAD

**Issue by liutiming** [yihui/yihui.org#124]
Hi益辉，想听听你对文章分类的看法：我看到你的hugo themes 一般都是有分类功能的，但是你自己却没有用，这也是极简的一种生活方式吗？

**Comment by yihui** [comment]
算是吧。以前我也用分类和标签，但随着我的[决策疲劳](https://en.wikipedia.org/wiki/Decision_fatigue)越来越严重，我就把这些细枝末节的决策都去掉了，不想浪费脑子去安排文章分类，要让自己写文章的初始阻力尽量小。

**Comment by liutiming** [comment]
嗯，而且分类和标签第一要标准化，第二经常过一会儿就想翻改一次，会有很多阻力。

https://obsidian.md/ 这个记笔记的软件还是很有意思的，是用markdown，而且找笔记是用生成的地图而不是分类，说不定你会喜欢
