### ISSUE TITLE
Tutorial on R Markdown at DSM

### ISSUE THREAD

**Issue by yihui** [yihui/yihui.org#14]
This is an R Markdown tutorial to be given at the [Melbourne Data Science Week](http://www.datasciencemelbourne.com/medascin2017/session/r-markdown-ecosystem-reports-papers-dashboards-books-websites-and-presentations/).

## Software installation

In this tutorial, we will use R and a few R packages. RStudio is optional but I'll use it. I'll also mention what you could do if you do not prefer using RStudio.

- [The latest version of R](https://cran.rstudio.com/) (3.4.0) is recommended but not required. Just do not use a version of R that is too old (e.g. two years older than the latest).

- Install these R packages:

```r
install.packages(c('rmarkdown', 'bookdown', 'tufte', 'rticles', 'xaringan', 'devtools'))
devtools::install_github(c('rstudio/blogdown'))
```

- There may be a few more packages that I will demo briefly, and you do not have to preinstall them.

- RStudio: https://www.rstudio.com (again, the very latest version is recommended but not required)

- LaTeX: https://www.latex-project.org/get/

- (Optional) Git. I don't have a recommendation on how to install it, but perhaps the easiest way is https://desktop.github.com if you use Github.

## Slides and examples

I'll post links here before the tutorial starts (the files will be small enough, so you should not worry about downloading issues). Please come back to this page before the tutorial (perhaps in the evening of May 29).

1. Slides: https://slides.yihui.name/2017-DSM-rmarkdown-Yihui-Xie.html

1. An R Markdown document example:

    - document: http://slides.yihui.name/rmd-doc.Rmd
    - references: http://slides.yihui.name/rmd-demo.bib

1. An R Markdown presentation example: http://slides.yihui.name/rmd-pres.Rmd

1. A bookdown demo: https://github.com/rstudio/bookdown-demo

## Who are you and what do you want to learn?

Please feel free to add your comments here to let me know more about you, such as the level of your R skills (so that I won't bore or scare you to death), what you expect me to teach, and what major problems you have got in your daily work (happy or unhappy with R Markdown?). The more prior information I know about the audience, the more effective the tutorial will be. I'll try to adjust the content according to your feedback in advance. If you don't want to post the information in the public, please also feel free to email me in private. Thanks!

## Misc

Please note that your WiFi connection may take 10 minutes for KPMG to approve after you send the application, so please do this as soon as you arrive at the meeting room.

**Comment by johngayler** [comment]
Hi Yihui, 

I've been using R for 6 months and write all of my reports in rmarkdown and love it.

I would love to learn how to make 'sexy' looking reports, particularly when in slide format, how to better use parameters, and best practices for creating tables that use inline code (something that looks and behaves like DT). 

I can show you clearer examples of what I've been doing and what I would like to be able to do in the tutorial. 

Thanks!

John

**Comment by RuOnAMonday** [comment]
Hi Yihui,

I've done the R programming course (including assignments) offered by Johns Hopkins Uni on cousera but haven't really used it for work yet, but would like to. So anything I can learn here will be beneficial.

Also I'm not very clear on what to download here? LaTeX: https://www.latex-project.org/get/
Will you be using an online tool or did you want us to download MikTex/Protext etc (if using Windows). Thanks!

Cheers,
Ru

**Comment by yihui** [comment]
@johngayler Thanks for the information. That is helpful.

@RuOnAMonday For Windows users, MikTeX is probably the best choice.

**Comment by TonyLadson** [comment]
Hi Yihui,

I've been using R and Rstudio for a few years and have recently been using R notebooks.  I started documenting my work using `bookdown::pdf_document2` and have begun to cross-reference tables and figures.  Keen to learn some tricks and get better and more efficient at documenting analysis.  Would like to  learn about citations and bibliographies.  Would like to be able to produce larger reports with lists of tables, lists of figures, report sections.  Keen to learn about making presentations.

I blog at https://tonyladson.wordpress.com/ which includes some R posts.

**Comment by charitylaw** [comment]
Hi Yihui, 

I've been using R and Rstudio for data analysis for ten (?) years now. I still find R scripts the fastest and most direct way to get results - it works well for me if I'm the only one looking at the results. But often I need to create reports with output and text descriptions to send to collaborators. I used to do this on LaTeX or Sweave, but R Markdown/Notebooks has made the documentation process a lot easier. Having said that, my go-to is still R scripts. I find that it is still a lengthy process to convert R scripts to reports, using either R Markdown or Notebooks, because output/plots need to be carefully formatted to display nicely (which may require changes to the R code itself). I have a dilemma every time I make minor code changes, now I need to update both the R script and Rmd file to keep the two consistent. I'm probably not going about this in the most efficient way. I'd love to hear what you're practice is, or what you would suggest to make this process consistent, non-repetitive, and efficient.

Thanks! I look forward to tomorrow's workshop.

**Comment by k-j-watson** [comment]
Hi Yihui,

I have used R at university for statistics and forecasting subjects, and also for about 6 months at work. I haven't used R markdown before, I've just used scripts mainly for data mining and modelling. I think learning anything about R markdown will be beneficial for me, even just having more awareness of what I can do with it.

See you tomorrow,
Kim

**Comment by farshid-vahid** [comment]
Hi Yihui,
I am a lecturer. I use different software and programming languages for different tasks. My goal is to develop online material for my courses. It is important to me that students are not restricted to any particular software or programming language.
Cheers,
Farshid
