### ISSUE TITLE
语言代码错了

### ISSUE THREAD

**Issue by CyrusYip** [yihui/yihui.org#1483]
https://yihui.org/cn/2022/07/river-god/

https://yihui.org/en/2023/04/get-objects/

![image](https://user-images.githubusercontent.com/60951091/236389949-4060de5a-3d83-45fd-bbc2-9a9a149c7905.png)

这两篇文章都是 `en-us`，国家代码应该大写（ https://github.com/earfanfan/yuanfan/pull/573#issue-1697072382 ）。可以改成 `en-US` 和 `zh-CN`。

**Comment by yihui** [comment]
谢谢，早就想修这个问题，一直没动力。既然你提了，我就修了它吧。
