### ISSUE TITLE
大哥，链接老旧，404！404 啦！

### ISSUE THREAD

**Issue by zsdycs** [yihui/yihui.org#1504]
啊，您终于来了，看看他们吧，都在这里了。👇

https://github.com/yihui/yihui.org/blob/3ed5eb97a47da70822b93d426ec03a361e8e8322/content/cn-vitae.md?plain=1#L313-L315

**Comment by yihui** [comment]
多谢相告！看样子是 Github 终于把十年前的下载功能取消掉了。我会找个时间修一下的。

**Comment by yihui** [comment]
修理完毕。谢谢。

https://github.com/yihui/yihui.org/blob/d266dc2a67f7a548f3dbf9c099e53dcc5f06bfcf/content/cn-vitae.md#L313-L315
