### ISSUE TITLE
菜单有多余的左外边距

### ISSUE THREAD

**Issue by CyrusYip** [yihui/yihui.org#1535]
![image](https://github.com/yihui/yihui.org/assets/60951091/545c3ca8-315c-481f-8493-f14a356650c5)

菜单在移动设备应该是居中吧？

**Comment by yihui** [comment]
去掉了小屏幕上的左边距。谢谢！

不想弄居中对齐了。

**Comment by CyrusYip** [comment]
我试了下调成居中对齐，改好一些地方，又出现新问题。完全就是这张图的情形。

![image](https://media.tenor.com/QWdPngpHxZ8AAAAd/family-guy-css.gif)

**Comment by yihui** [comment]
居中应该不难，我就是懒得弄了。
