### ISSUE TITLE
中文标点导致删除线 `~~` 失效

### ISSUE THREAD

**Issue by Shitao5** [yihui/yihui.org#1548]
在考古益辉的博客时发现 [买房还是租房？](https://yihui.org/cn/2018/04/renting/) 博客中有一句：

> 我要是发大财了，我就天天只写我自己想写的代码，干掉期刊，做个养眼的中文书籍模板（bookdown），正经做个厨子，任意时间看看书、写写博客、打打球，~~每顿饭三碗稀饭一碗放白糖一碗放红糖一碗倒掉，~~给我的中小学捐点钱。

这句话里边删除线的效果没有出现，根据我使用 Markdown 的经验，应该是中文的逗号 `，` 导致的。本想提 Pr，又想到或许益辉有其他大招解决，所以留一个 issue。

**Comment by yihui** [comment]
谢谢，我没有大招。这主要是因为 Markdown 工具通常是外国人开发，而外语里通常用空格分隔单词，所以很多工具没有照顾到中日韩这些不用空格的语言。删除线语法要求后面跟着空格。
