### ISSUE TITLE
繁体字怪怪的

### ISSUE THREAD

**Issue by CyrusYip** [yihui/yihui.org#1553]
https://yihui.org/cn/2016/12/ceo/

---

Brave 浏览器：

![image](https://github.com/yihui/yihui.org/assets/60951091/5a155f24-152b-42cd-8ade-9034150b5705)

![image](https://github.com/yihui/yihui.org/assets/60951091/e6306a1c-0d53-4f3e-b61b-1924fd567b04)

---

Firefox 浏览器：

![image](https://github.com/yihui/yihui.org/assets/60951091/0f86d679-c8f8-443e-9e4e-5f4553fa3683)

![image](https://github.com/yihui/yihui.org/assets/60951091/94ee8ce4-3e2b-4d72-a936-f261e867b223)

**Comment by yihui** [comment]
这应该是因为我用的[文鼎 PL 简中楷](https://github.com/yihui/yihui.org/discussions/1547)字体中没有繁体支持，而你的系统中也没有别的楷体，所以这几个繁体字就用了默认字体。我的苹果系统下有楷体，所以浏览器就用了系统楷体：

<img width="561" alt="image" src="https://github.com/yihui/yihui.org/assets/163582/a9ccffe1-5ab3-43a4-a582-2fb2bdecb6c7">

这问题麻烦就麻烦在中文字体太少有开源版本可以用了。

**Comment by CyrusYip** [comment]
原来如此，我用的 Arch Linux 确实没装楷体。

**Comment by chuxinyuan** [comment]
@yihui 你整的那个精简版的高频字库我已经用上了，华为手机上也可以看到漂亮的楷体了，很舒服。

**Comment by chuxinyuan** [comment]
**2024-06-17 更新：**

注意，下面的方法不可行。我刚打电话问了，客服说：“这个属于云端嵌入式，这种模式要收费，但是拆分字体是不允许的，这是原则性问题”，所以，这个事情只能夭折了。

我已删除我仓库里涉及方正楷体的代码和字体。

----

~~我从方正楷体借了 13 个字（甝字为我借的）暂时可以解决问题。~~

```css
@font-face {
  font-family: 'FandolKai';
  src: url('https://cdn.jsdelivr.net/gh/chuxinyuan/cron/fonts/Extra-FZKTK-cxy.woff2') format('woff2');
}
```

测试代码如下：

```html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>缺失字体测试</title>
    <style>
        @font-face {
            font-family: 'FandolKai';
            src: url('https://cdn.jsdelivr.net/gh/chuxinyuan/cron/fonts/Extra-FZKTK-cxy.woff2') format('woff2');
            font-weight: normal;
            font-style: normal;
        }

        .test-font {
            font-family: 'FandolKai', sans-serif;
            font-size: 48px;
        }
    </style>
</head>
<body>
    <div class="test-font">甝貢獻對義較為別專謝輝讓寫</div>
</body>
</html>
```

**Comment by chuxinyuan** [comment]
根据[中文开源字体集](https://drxie.github.io/OSFCC/)，AR PL KaitiM Big5 和 AR PL UKai 包含繁体的楷体（当然还有其它繁体楷体，只是感觉简体用文鼎的，繁体如果也用文鼎的，整体上风格更一致）。我在[天天字体网](https://www.ttfont.com/font-details/1704957/)测试了下，AR PL KaitiM Big5 可以完美显示这 13 个字的楷体。

我在 Debian 官网上看到，Debian 也在用文鼎的楷体，进一步确认这个字体确实是开源字体。其中：

- fonts-arphic-ukai = AR PL KaitiM Big5 + AR PL KaitiM GB + 一些额外的字符，详见：<https://packages.debian.org/stable/fonts/fonts-arphic-ukai>
- fonts-arphic-bkai00mp = AR PL KaitiM Big5，详见：<https://packages.debian.org/sid/fonts-arphic-bkai00mp>
- fonts-arphic-gkai00mp = AR PL KaitiM GB，详见：<https://packages.debian.org/sid/fonts-arphic-gkai00mp>

我在 [CTAN](https://ctan.org/tex-archive/fonts/arphic-ttf) 上找到了如下字体：

- bkai00mp.ttf，楷体繁体
- bsmi00lp.ttf，宋体繁体
- gbsn00lp.ttf，宋体简体
- gkai00mp.ttf，楷体简体

测试代码如下：

```html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>缺失字体测试</title>
    <style>
        @font-face {
            font-family: 'Kaiti';
            src: url('https://cdn.jsdelivr.net/gh/chuxinyuan/cron/fonts/bkai00mp-cxy.woff2') format('woff2');
            font-weight: normal;
            font-style: normal;
        }
        .Kai-font {
            font-family: 'Kaiti', sans-serif;
            font-size: 48px;
        }
    </style>
</head>
<body>
    <div class="Kai-font">甝貢獻對義較為別專謝輝讓寫</div>
</body>
</html>
```

**Comment by CyrusYip** [comment]
现在显示正常了。

![Screenshot_20240624_083956](https://github.com/yihui/yihui.org/assets/60951091/eb059bc1-08cc-4d93-a842-9a5f79fe3994)

**Comment by yihui** [comment]
我们感谢 @chuxinyuan 的执着。

**Comment by CyrusYip** [comment]
@chuxinyuan 推荐你用 JS Bin 分享网页代码，它可以直接预览，示例（ https://github.com/yihui/yihui.org/issues/1553#issuecomment-2172336887 ）：<https://jsbin.com/mituwicuge/2/edit?html,output>.

![image](https://github.com/yihui/yihui.org/assets/60951091/f77b027f-4d61-490b-b29a-65bb8f4a390f)

**Comment by chuxinyuan** [comment]
@CyrusYip  JS Bin 分享网页代码确实方便，下次把代码和结果一并贴出来，一目了然，大家都省事。

@yihui 都是站在巨人的肩膀上，做点边边角角的工作，尤其是你把思源字体的解决方案从思路到完整代码都放出来了，剩下举一反三的事情出成果也只是时间的函数。

话说台湾这哥们所言非虚，我第一次 PR 被合并的时候也是兴奋了好长时间。
