### ISSUE TITLE
markdown vignettes 超链接失效

### ISSUE THREAD

**Issue by Shitao5** [yihui/yihui.org#1617]
益辉好，在阅读博客文章 [*Snap Slides: a Lightweight HTML Presentation Framework*](https://yihui.org/en/2023/09/snap-slides/) 时发现以下超链接失效：

https://github.com/yihui/yihui.org/blob/0eb3b5946fd0d03a789852d9205548eaf00fe7fa/content/en/2023-09-21-snap-slides.md?plain=1#L213-L215

在 **markdown** 包的 CRAN 页面已看不到 vignettes 页面，但 **litedown** 有：

![image](https://github.com/user-attachments/assets/dd61081e-9ff3-4a88-8e69-d2a0affe7b39)

或许需将失效的链接改为：<https://cran.r-project.org/web/packages/litedown/vignettes/slides.html>，考虑到和文章中其他内容相关，便没有提直接修改链接的 PR。

**Comment by yihui** [comment]
是的，不止这一个链接，其它 markdown 包相关的链接都要改：https://github.com/search?q=repo%3Ayihui%2Fyihui.org%20%22https%3A%2F%2Fcran.r-project.org%2Fweb%2Fpackages%2Fmarkdown%2Fvignettes%2F%22&type=code 这两天实现 litedown 里的数学公式交叉引用简直让我昏了头（好歹终于实现出来了），现在要睡觉去了，明天再改。谢谢！

**Comment by Shitao5** [comment]
恭喜！大晚上一点多还在吭哧吭哧写代码，注意身体多休息。最近开始用 litedown 做幻灯片，感觉简单又酷炫，绝对是俺的不二之选。

**Comment by yihui** [comment]
链接已修复。

对于 litedown 幻灯片，我自己有个不太喜欢的地方是无法光速翻页，翻页时必须有个短暂的滚动过程。当然，为了弥补这个缺陷，我提供了预览模式，可以在预览模式下快速找到想去的那一页，然后按住 Ctrl 或 Alt 键同时点击那一页就可以跳过去了。即便这样，我还是觉得有点不方便。

我对 litedown 最满意的地方是我用两百行代码实现出来的分页排版效果，网页打印 PDF 还不赖。TeX/LaTeX 是对排版问题提供了精确的解决方案，而我提供了一个超级简单的近似解决方案，代码量可能只有百万分之一。我打算把 litedown 的书写完后找个出版社直接打印网页版，完全绕过 LaTeX。要是没出版社愿意吃这螃蟹，我就自助出版好了。

**Comment by Shitao5** [comment]
litedown 幻灯片的预览模式非常好用。从俺一个外行人的角度看，光速翻页是否可以通过加快翻页滚动的速度甚至取消翻页滚动的效果来达成嘞？另外，目前 litedown 幻灯片似乎都是整页展示，不能像 xaringan 一样通过 `--` 在同一页一段段地展示内容。

litedown 分页排版绝对惊艳！当时知道有这个功能就在介绍页面摁下 `p` 键，很震撼。没想到只用了两百多行代码，厉害啊！支持直接打印出版（若自助且需要，俺可尽绵薄之力），不过需注意双面打印时页码若不是居中显示的话，需区分奇偶页（奇数页页码靠右，偶数页页码靠左）。

**Comment by yihui** [comment]
滚动速度不由得我控制，它取决于用户鼠标设置的滚动速度和浏览器相应的响应速度；普通网页滚多快，幻灯片就只能滚那么快。

分段显示 `--` 的功能我考虑过一段时间，技术上可以实现，只是会稍微增加一点代码的复杂度。等我哪天忍不了这个需求了再重新考虑。我甚至考虑过分屏显示的功能，就是 xaringan 里按 c 跳出新窗口、可以单独拖到投影上给观众看，而自己按 p 看着自己带注释的版本讲。这个对我更有用，但实现起来恐怕更复杂。

litedown 奇偶页排版很容易，不管是页脚元素可以左右对调位置，而且奇偶页的页边距也可以不对称、可对调。我只是还没时间写文档。

**Comment by Shitao5** [comment]
明白了。有了按 c 跳出新窗口、按 p 显示注释的功能，现场讲就不慌了。若是后面分段显示和分屏显示都有了，做幻灯片方面几乎可以替代 xaringan 了。

> 我只是还没时间写文档。

俺做一个耐心的体验用户嘿嘿。
