### ISSUE TITLE
博客文章阅读次数插件

### ISSUE THREAD

**Issue by Miachol** [yihui/yihui.org#18]
hi,
益辉, 现在有没有简单的插件可以记录博客文章的阅读次数？另外,https://github.com/overtrue/share.js 似乎作为博客推送的分享插件是一个不错的选择

**Comment by yihui** [comment]
我母鸡啊。我不在乎我的博客阅读次数，我觉得像阅读次数啊，点赞人数啊，这些东西基本上都是用来装点门面的。我比较极端，装门面的东西我一般都懒得装。

我前一个主题里我还放了微博和推特的分享按钮，现在的主题我连这两个按钮都砍掉了。根据我的经验，真正点击它们的人并不多（当然可能只是我的博客人气太低），放那儿只是浪费空间和制造视觉混乱。社交媒体的话题，我以后的博客会谈，我现在比较反社交。

**Comment by Miachol** [comment]
嗯嗯 我是觉得blogdown非常方便 可以再多弄一些小插件 用户可以自己选择用或是不用 http://busuanzi.ibruce.info/ 一个js的简易计数器

**Comment by yihui** [comment]
嗯，你自己的网站你做主，想装啥都可以自行安装。我选择我正式支持的库的时候一般会偏向保守，因为一次性支持通常都很容易，问题是做软件通常都不是一次性的事情，一旦要支持什么，就得把锅背到底。把锅背到底的意思是，那个库的所有问题将来都会由我来背，多数用户都不会在乎这个库是不是我编写的，出了问题首先会来找我。恕臣妾无能，实在维护不了这么多库。我只能搭好通用框架，具体的细节功能问题，我不想插手太多。网页技术方面的锅，尤其难背：https://d.cosx.org/d/419339/4
