### ISSUE TITLE
Feed does not validate.

### ISSUE THREAD

**Issue by qinwf** [yihui/yihui.org#6]
See https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fyihui.name%2Fen%2Findex.xml

**Comment by yihui** [comment]
Thanks for the report! I have been using feedly.com and have not seen a problem with it yet. I know how to fix this issue (set `baseurl` to `https://yihui.name/`), but normally I don't like writing out a full URL anywhere.

**Comment by yihui** [comment]
I have defined my own [RSS feed template](https://github.com/rbind/yihui/blob/master/layouts/rss.xml) and fixed this issue.
