### ISSUE TITLE
脚注有问题

### ISSUE THREAD

**Issue by magic-moon** [yihui/yihui.org#84]
clone这个仓库和主题，hugo之后无法生成脚注。依然保持^[]的样子。

**Comment by yihui** [comment]
对，这是因为 Hugo 后来更换了 Markdown 渲染器，而它并不支持行内脚注：https://github.com/yuin/goldmark/issues/47

我自己的网站现在仍然是用 Hugo 0.25.1 编译的。

**Comment by magic-moon** [comment]
居然是这样，谢谢

**Comment by yihui** [comment]
不客气。另外为了避免引起误解，你的个人网站上可以把我的头像换掉吗？谢谢！
