### ISSUE TITLE
time span of articles

### ISSUE THREAD

**Issue by zhaofeng-shu33** [yihui/yihui.org#85]
hi, yihui. I am a reader of your blog.
I find your blog starts from your fourth year of undergraduate education. Do you have ever considered put your diaries before that time in your blog? I have tried to do so recently and find some parts are very tedious because old articles are in microsoft word format. The older are scanned version of notebooks. You can check my github pages if you want and any comments on this issue is welcome.

**Comment by yihui** [comment]
我上大学后没写多少日记，可能用笔写过几篇，但现在应该是找不到了。高中及以前的日记本应该也都散失了。我现在能做的就是有空时凭记忆把那时候的一些事再写出来。

你的旧 Word 文档可以用 Pandoc 转成 Markdown。扫描的日记本不妨就直接放图片嘛，非要整理的话，也许有光学识别的软件可用。

**Comment by zhaofeng-shu33** [comment]
Thanks for your suggestion. `pandoc` works for docx. My old documents are mostly in `doc` format, which is different from `docx`. As far as know, there is some software which can convert `doc` to `docx` in batch mode.
