### ISSUE TITLE
p 元素中的 img 居中

### ISSUE THREAD

**Issue by zsdycs** [yihui/yihui.org#87]
hi，@yihui

https://github.com/rbind/yihui/blob/23fe62cdeda1905704fe7db088d3c50ce8ed920e/static/js/center-img.js#L15

我发现这一行不能很好的达到效果(可以用较窄长的图片测试)。

如果要让 img 在 p 中正确居中，建议设置 img:
```css
display: block;
margin: auto;
```

**Comment by yihui** [comment]
谢谢反馈，不过请参见：https://github.com/yihui/hugo-ivy/pull/6 真是巧了，一周内有两个人分别跟我提起这个问题。

对窄长图片来说，我想不出用 `display: block` 加 `margin: auto` 居中图片和用我的 JS 办法居中有什么区别，你的窄长的意思是指高度超高吗？对超过父元素宽度的超宽图片也许有区别（尽管我也怀疑）。给个例子看看？

**Comment by zsdycs** [comment]
哈，太巧了。😄

[这个图片就可以](https://cdn.jsdelivr.net/gh/zsdycs/lipk.org/static/images/watchdog.gif) 测试出来效果。

我是在手机上发现这个问题的，在较小宽度显示时，图片居中后左右宽度不一致的问题会比较明显。

**Comment by yihui** [comment]
https://jsfiddle.net/sg45k68p/ 有何区别？

**Comment by zsdycs** [comment]
实在抱歉，找到了原因，代码没有问题。

是因为我在 P 开头增加了 `&emsp;&emsp;` 作为段落缩进， 转义字符在控制台难以看出来区别。

https://jsfiddle.net/zsdycs/dkf0szcu/

（真相大白）

**Comment by yihui** [comment]
哦，明白了。看样子你已经解决了：https://github.com/zsdycs/lipk.org/commit/49072d420555de430eb204e36eae0ed696bfd5bb

我个人不太倾向于同时使用首行缩进和段落间空行。不过这是你自己的审美偏好，自己觉得舒服就行。
