### ISSUE TITLE
document 为何不是 d 哇？

### ISSUE THREAD

**Issue by zsdycs** [yihui/yihui.org#88]
### 传了 document 命名为 d，可是还是用的 document

https://github.com/rbind/yihui/blob/703d24b0ce678150a67749ed417dcef532f1b304/static/js/load-typekit.js#L1
https://github.com/rbind/yihui/blob/703d24b0ce678150a67749ed417dcef532f1b304/static/js/load-typekit.js#L16

这一行和后面的代码风格不一致哇。😧
https://github.com/rbind/yihui/blob/703d24b0ce678150a67749ed417dcef532f1b304/static/js/load-typekit.js#L3

**Comment by yihui** [comment]
谢谢！
